version: "3.8"

services:
  mysql_5_7:
    image: mysql/mysql-server:5.7
    container_name: mysql_blue
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "33010:3306"
    volumes:
      - ./init_db_mysql_v57:/docker-entrypoint-initdb.d
      - ./scripts:/scripts
    networks:
      - mysql_net

  mysql_8_0:
    image: mysql:8.3.0
    container_name: mysql_green
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "33011:3306"
    volumes:
      - ./init_db_mysql_v8:/docker-entrypoint-initdb.d
      - ./scripts:/scripts
    networks:
      - mysql_net

networks:
  mysql_net:
    driver: bridge
